### ISSUE TITLE
Local images and/or screenshots

### ISSUE THREAD

**Issue by topche** [LAB02-Research/HASS.Agent-Notifier#20]
Which path I have to use , when I need to send notification with image ?
I did try to use as other notifications /local/pics/xxxx.jpg with no success.
When I try to use http://some.domain/where/stored.jpg it is work with no issue

**Comment by LAB02-Admin** [comment]
Did you try the examples here: https://hassagent.readthedocs.io/en/latest/notifications/notification-usage-and-examples/
