### ISSUE TITLE
I can see notificacions in Windows 10

### ISSUE THREAD

**Issue by josemabcn** [LAB02-Research/HASS.Agent-Notifier#21]
Dears,

I can see notifications in windows 10. When I check the notifications by HASS.Agent Configuration -> Notifications with the test notification button it works well:

![AgentNotifications](https://user-images.githubusercontent.com/19243737/179373282-5aafab91-db68-4c19-9ad8-91adc5ef6501.jpg)

But when I check the notification in Home Assistant don't works, and any error in the logs is showed. 

Any help about this?,

Thanks,

**Comment by LAB02-Admin** [comment]
Hey @josemabcn,

Did you follow the debugging guide? 

https://hassagent.readthedocs.io/en/latest/notifications/notification-debugging-ha-side/

**Comment by josemabcn** [comment]
> Hey @josemabcn,
> 
> Did you follow the debugging guide?
> 
> https://hassagent.readthedocs.io/en/latest/notifications/notification-debugging-ha-side/

Dear LAB02-Admin,

Thanks for your help. I installed the log viewer, then, from developers tools->service the following code:

`service: notify.pc_jose
data:
  message: The garage door has been open for 10 minutes.
  title: Your Garage Door Friend
  target: platform specific
  data: platform specific`

And the logs show:


`2022-07-18 20:23:50 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: expected dict for dictionary value @ data['data']
2022-07-18 20:23:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140664773835552] Error handling message: expected dict for dictionary value @ data['data']. Got None (invalid_format)`

But, when I send the test notification from the Configuration->Notification not errors are showed.

**Comment by josemabcn** [comment]
Solved, 
The problem was about the ip address in configuration.yaml:

The ip address like 192.xxx.xxx.033:5115 don't works, but the ip address 192.xxx.xxx.33:5115 works OK.

Thanks
