### ISSUE TITLE
multiple computers to notify

### ISSUE THREAD

**Issue by mortalone** [LAB02-Research/HASS.Agent-Notifier#24]
hi. i was wondering if it is possible to set up multiple computers.

notify: 
  name: "hass agent test device 1"
  platform: hass_agent_notifier
  resource: http://{device_ip1}:5115/notify

  name: "hass agent test device 2"
  platform: hass_agent_notifier
  resource: http://{device_ip2}:5115/notify

**Comment by LAB02-Admin** [comment]
There are some examples you can use in this ticket: #19
