### ISSUE TITLE
After install nothing starts

### ISSUE THREAD

**Issue by Bollemp3** [LAB02-Research/HASS.Agent-Notifier#27]
Hi, I'm trying to install the agent on a Windows 10 enterprise 21H2 Dutch version (clean install) but it won't start after the installation. The configuration screen won’t start.
 after a restart and starting  the agent also.

Now I suspect it's because I have a TV connected to the PC and not a monitor.  Is anything known issues about that?  

I have it running on my laptop with the same version of Windows, this works great!

**Comment by LAB02-Admin** [comment]
That's odd, the TV shouldn't be a problem. Could you try with this beta:

https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0-beta2

Otherwise, could you see if there's anything interesting in the logs (`%appdata%\LAB02 Research\HASS.Agent\logs`)
