### ISSUE TITLE
Bug: don't generate errors if target IP doesn't answer

### ISSUE THREAD

**Issue by pannal** [LAB02-Research/HASS.Agent-Notifier#8]
Hey there, thank you for this app!

I have one little issue that I'd love to be addressed: My notification script in HA uses multiple targets (phone, PC, etc.). If my PC is off, the notification causes an error traceback in HA due to the PC not answering and kills the rest of the script execution.

Would it be possible to add an option to catch network errors and not raise them?

**Comment by LAB02-Admin** [comment]
Sure thing!

**Comment by LAB02-Admin** [comment]
Fixed in the [latest release](https://github.com/LAB02-Research/HASS.Agent-Notifier/releases/tag/v2022.3.15), thanks for the tip :)
